name: Generate Sitemap

on:
  push:
    branches: [ gh-pages ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Create Sitemap Generator Script
        run: |
          cat > generate-sitemap.js << 'EOL'
          const fs = require('fs');
          const path = require('path');
          const { parseString } = require('xml2js');
          const util = require('util');
          const parseXml = util.promisify(parseString);

          async function generateSitemap() {
            try {
              // Read existing sitemap if it exists
              let existingUrls = new Set();
              if (fs.existsSync('sitemap.xml')) {
                console.log('Reading existing sitemap.xml...');
                const existingSitemap = fs.readFileSync('sitemap.xml', 'utf8');
                const result = await parseXml(existingSitemap);
                if (result.urlset && result.urlset.url) {
                  result.urlset.url.forEach(url => {
                    existingUrls.add(url.loc[0]);
                  });
                }
                console.log('Found', existingUrls.size, 'existing URLs');
              }

              // Read games data
              console.log('Reading games.js file...');
              const gamesContent = fs.readFileSync('js/games.js', 'utf8');
              const gamesMatch = gamesContent.match(/const\s+games\s*=\s*(\[[\s\S]*\])\s*;/);
              if (!gamesMatch) {
                throw new Error('Could not find games array in file');
              }
              
              const games = eval(gamesMatch[1]);
              console.log('Found', games.length, 'games');

              // Generate URLs from games
              const baseUrl = 'https://cool2fun.github.io';
              
              // Add homepage URL
              const staticUrls = [
                {
                  url: baseUrl + '/',
                  priority: '1.0',
                  changefreq: 'daily'
                }
              ];
              
              // Combine all URLs
              const gameUrls = games.map(game => ({
                url: baseUrl + game.link,
                priority: '0.8',
                changefreq: 'weekly'
              }));
              
              const allUrls = [...staticUrls, ...gameUrls];
              console.log('Total URLs:', allUrls.length);

              // Generate new sitemap content
              const sitemapContent = `<?xml version="1.0" encoding="UTF-8"?>
              <urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
                ${allUrls.map(urlObj => `
                  <url>
                    <loc>${urlObj.url}</loc>
                    <lastmod>${new Date().toISOString().split('T')[0]}</lastmod>
                    <changefreq>${urlObj.changefreq}</changefreq>
                    <priority>${urlObj.priority}</priority>
                  </url>
                `).join('')}
              </urlset>`.trim();

              console.log('Writing updated sitemap.xml...');
              fs.writeFileSync('sitemap.xml', sitemapContent);
              console.log('Sitemap updated successfully!');
            } catch (error) {
              console.error('Error generating sitemap:', error);
              process.exit(1);
            }
          }

          generateSitemap();
          EOL

      - name: Install xml2js
        run: npm install xml2js

      - name: Generate Sitemap
        run: node generate-sitemap.js

      - name: Commit and Push Changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add sitemap.xml
          git commit -m "Update sitemap.xml" || echo "No changes to commit"
          git push