name: Generate Sitemap

on:
  push:
    branches: [ gh-pages ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Create Sitemap Generator Script
        run: |
          cat > generate-sitemap.js << 'EOL'
          const fs = require('fs');
          const path = require('path');

          try {
            console.log('Reading games.js file from /js directory...');
            const gamesContent = fs.readFileSync('js/games.js', 'utf8');
            console.log('games.js content length:', gamesContent.length);

            // Extract array from const declaration
            console.log('Extracting games array...');
            const gamesMatch = gamesContent.match(/const\s+games\s*=\s*(\[[\s\S]*\])\s*;/);
            if (!gamesMatch) {
              throw new Error('Could not find games array in file');
            }
            
            // Safely evaluate the array
            console.log('Evaluating games array...');
            const games = eval(gamesMatch[1]);
            console.log('Found', games.length, 'games');

            // Your website URL
            const baseUrl = 'https://cool2fun.github.io';

            console.log('Generating sitemap content...');
            // Generate sitemap content
            const sitemapContent = `<?xml version="1.0" encoding="UTF-8"?>
            <urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
              ${games.map(game => `
                <url>
                  <loc>${baseUrl}${game.link}</loc>
                  <lastmod>${new Date().toISOString().split('T')[0]}</lastmod>
                  <changefreq>weekly</changefreq>
                  <priority>0.8</priority>
                </url>
              `).join('')}
            </urlset>`.trim();

            console.log('Writing sitemap.xml...');
            fs.writeFileSync('sitemap.xml', sitemapContent);
            console.log('Sitemap generated successfully!');
          } catch (error) {
            console.error('Error generating sitemap:', error);
            process.exit(1);
          }
          EOL

      - name: Generate Sitemap
        run: node generate-sitemap.js

      - name: Commit and Push Changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add sitemap.xml
          git commit -m "Update sitemap.xml" || echo "No changes to commit"
          git push