name: Generate Sitemap

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate-sitemap:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          
      - name: Debug Files
        run: |
          ls -la
          cat games.js
          
      - name: Generate Sitemap
        run: |
          node -e "
          const fs = require('fs');
          const games = require('./games.js');
          
          const domain = 'https://cool2fun.github.io';
          
          let xml = '<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n';
          xml += '<urlset xmlns=\"http://www.sitemaps.org/schemas/sitemap/0.9\">\n';
          
          xml += `  <url>
              <loc>${domain}</loc>
              <lastmod>${new Date().toISOString().split('T')[0]}</lastmod>
              <changefreq>daily</changefreq>
              <priority>1.0</priority>
          </url>\n`;

          games.forEach(game => {
              xml += `  <url>
                  <loc>${domain}${game.link}</loc>
                  <lastmod>${new Date().toISOString().split('T')[0]}</lastmod>
                  <changefreq>weekly</changefreq>
                  <priority>0.8</priority>
              </url>\n`;
          });

          const categories = new Set();
          games.forEach(game => {
              game.category.split(',').forEach(cat => categories.add(cat.trim()));
          });

          categories.forEach(category => {
              xml += `  <url>
                  <loc>${domain}/category?category=${encodeURIComponent(category)}</loc>
                  <lastmod>${new Date().toISOString().split('T')[0]}</lastmod>
                  <changefreq>weekly</changefreq>
                  <priority>0.7</priority>
              </url>\n`;
          });

          xml += '</urlset>';
          fs.writeFileSync('sitemap.xml', xml);
          console.log('Sitemap generated successfully');
          console.log(xml);
          "

      - name: Commit and Push Changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add sitemap.xml
          git commit -m "Auto-update sitemap.xml" || echo "No changes to commit"
          git push