name: Generate Sitemap

on:
  workflow_dispatch:  # Cho phép chạy thủ công
  push:
    branches:
      - gh-pages
    paths-ignore:
      - 'sitemap.xml'  # Tránh vòng lặp vô tận

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || !contains(github.event.head_commit.message, 'Auto-update sitemap')

    steps:
      - uses: actions/checkout@v2
        with:
          ref: gh-pages

      - name: Generate Sitemap
        run: |
          echo '<?xml version="1.0" encoding="UTF-8"?>' > sitemap.xml
          echo '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' >> sitemap.xml
          
          # Homepage
          echo '  <url>
            <loc>https://cool2fun.github.io</loc>
            <lastmod>'$(date +%Y-%m-%d)'</lastmod>
            <priority>1.0</priority>
          </url>' >> sitemap.xml
          
          # Game pages
          for game in slope "3-pandas-in-japan" "retro-bowl" "run-3" "adam-and-eve-7" "boxing-random" "3d-bowling" "cookie-clicker-2" "drive-mad" "g-switch-4" "iron-snout" "little-alchemy-2" "mr-bullet" "vex-8" "papa-cherry-saga" "rooftop-snipers" "stick-merge-2" "rusher-crusher" "tag" "ball-sort-halloween" "subway-surfers" "super-mario" "blumgi-slime" "bouncy-woods" "chicken-merge"; do
            echo '  <url>
              <loc>https://cool2fun.github.io/'$game'.html</loc>
              <lastmod>'$(date +%Y-%m-%d)'</lastmod>
              <priority>0.8</priority>
            </url>' >> sitemap.xml
          done
          
          echo '</urlset>' >> sitemap.xml

      - name: Setup Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: Commit and Push
        run: |
          git add sitemap.xml
          git diff --quiet && git diff --staged --quiet || git commit -m "Auto-update sitemap"
          git push