name: Generate Sitemap

on:
  workflow_dispatch:
  push:
    branches:
      - gh-pages
    paths:
      - 'games.js'  # Chỉ trigger khi games.js thay đổi

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: gh-pages

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Generate Sitemap
        run: |
          # Tạo script để đọc games.js
          echo '
          const fs = require("fs");
          
          // Đọc và parse games.js
          const content = fs.readFileSync("games.js", "utf8");
          const gamesMatch = content.match(/const\s+games\s*=\s*(\[[\s\S]*?\]);/);
          const games = eval(gamesMatch[1]);
          
          // Tạo sitemap
          let xml = `<?xml version="1.0" encoding="UTF-8"?>
          <urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
            <url>
              <loc>https://cool2fun.github.io</loc>
              <lastmod>${new Date().toISOString().split("T")[0]}</lastmod>
              <priority>1.0</priority>
            </url>`;
          
          // Thêm URLs cho mỗi game
          games.forEach(game => {
            xml += `
            <url>
              <loc>https://cool2fun.github.io${game.link}</loc>
              <lastmod>${new Date().toISOString().split("T")[0]}</lastmod>
              <priority>0.8</priority>
            </url>`;
          });
          
          xml += "\n</urlset>";
          
          // Ghi ra file sitemap.xml
          fs.writeFileSync("sitemap.xml", xml);
          ' > generate-sitemap.js
          
          # Chạy script
          node generate-sitemap.js
          
          # Hiển thị kết quả
          cat sitemap.xml

      - name: Commit and Push
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git add sitemap.xml
          git diff --quiet && git diff --staged --quiet || git commit -m "Auto-update sitemap"
          git push