name: Generate Sitemap

on:
  push:
    branches:
      - gh-pages
    paths:
      - 'games.js'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Generate Sitemap
        id: sitemap
        run: |
          echo "Creating sitemap.xml"
          echo '<?xml version="1.0" encoding="UTF-8"?>' > sitemap.xml
          echo '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' >> sitemap.xml
          
          # Add homepage
          echo '  <url>' >> sitemap.xml
          echo '    <loc>https://cool2fun.github.io</loc>' >> sitemap.xml
          echo "    <lastmod>$(date +%Y-%m-%d)</lastmod>" >> sitemap.xml
          echo '    <priority>1.0</priority>' >> sitemap.xml
          echo '  </url>' >> sitemap.xml
          
          # Extract game URLs from games.js
          grep -o 'link: *"[^"]*"' games.js | while read -r line; do
            GAME_URL=$(echo "$line" | sed 's/link: *"\(.*\)"/\1/')
            echo "  <url>" >> sitemap.xml
            echo "    <loc>https://cool2fun.github.io${GAME_URL}</loc>" >> sitemap.xml
            echo "    <lastmod>$(date +%Y-%m-%d)</lastmod>" >> sitemap.xml
            echo "    <priority>0.8</priority>" >> sitemap.xml
            echo "  </url>" >> sitemap.xml
          done
          
          echo '</urlset>' >> sitemap.xml
          
          echo "Sitemap content:"
          cat sitemap.xml

      - name: Commit and Push
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git add sitemap.xml
          git commit -m "Update sitemap" || echo "No changes to commit"
          git push || echo "No changes to push"